version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gsandoo/spring-backend:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: no